# Generated by Django 5.0 on 2023-12-26 20:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_course_tasks_task_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курс'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задания', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(blank=True, default=[], to=settings.AUTH_USER_MODEL),
        ),
    ]
