# Generated by Django 5.0 on 2023-12-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_subject_profile_points_chat_message_subjectraiting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(blank=True, max_length=250, unique=True),
        ),
    ]
