# Generated by Django 5.0 on 2023-12-26 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_subject_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмет'},
        ),
        migrations.AlterModelOptions(
            name='subjectraiting',
            options={'verbose_name': 'Оценка ученика за предмет', 'verbose_name_plural': 'Оценка ученика за предмет'},
        ),
        migrations.AddField(
            model_name='subjectraiting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjectraiting',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='subjectraiting',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.subject', verbose_name='Предмет'),
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
    ]
